"""Tests for macOS packaging pipeline, spec validation, and bundle configuration."""

import ast
from pathlib import Path
import unittest


class TestPackagingMacOS(unittest.TestCase):
    """Verify all artifacts, scripts, and spec configurations for macOS distribution."""

    def setUp(self):
        self.repo_root = Path(__file__).resolve().parent.parent
        self.macos_pkg_dir = self.repo_root / "packaging" / "macos"
        self.assets_dir = self.repo_root / "packaging" / "assets"

    def test_all_required_files_exist(self):
        """Verify all mandated macOS packaging files exist in packaging/macos/."""
        required = [
            "migrator.spec",
            "build_macos.sh",
            "create_dmg.py",
            "build_dmg_background.py",
            "generate_icns.py",
            "entrypoint.py",
        ]
        for fname in required:
            target = self.macos_pkg_dir / fname
            self.assertTrue(target.is_file(), f"Missing required file: {target}")

    def test_spec_file_validity(self):
        """Verify macOS migrator.spec can be parsed as valid Python AST and contains required config."""
        spec_file = self.macos_pkg_dir / "migrator.spec"
        content = spec_file.read_text(encoding="utf-8")
        tree = ast.parse(content, filename=str(spec_file))
        self.assertGreater(len(tree.body), 0)

        # Check critical settings
        self.assertIn("agy-migrator", content)
        self.assertIn("AppIcon.icns", content)
        self.assertIn("antigravity_migrator", content)
        self.assertIn("antigravity_migrator/gui", content)
        self.assertIn("webview", content)
        self.assertIn("webview.platforms.cocoa", content)

    def test_build_macos_bundle_configuration(self):
        """Verify build_macos.sh configures a native GUI app bundle without Terminal launcher."""
        script_file = self.macos_pkg_dir / "build_macos.sh"
        content = script_file.read_text(encoding="utf-8")

        # Bundle must use direct binary as executable, not a Terminal-invoking launcher
        self.assertIn("<key>CFBundleExecutable</key>", content)
        self.assertIn("<string>agy-migrator</string>", content)
        self.assertIn("<key>CFBundlePackageType</key>", content)
        self.assertIn("<string>APPL</string>", content)
        self.assertIn("<key>NSHighResolutionCapable</key>", content)
        self.assertIn("<true/>", content)

        # Must NOT contain Terminal.app launcher
        self.assertNotIn("tell application \"Terminal\"", content)
        self.assertNotIn("launcher", content)

    def test_entrypoint_psn_handling(self):
        """Verify entrypoint strips macOS Process Serial Number argument."""
        entrypoint_file = self.macos_pkg_dir / "entrypoint.py"
        content = entrypoint_file.read_text(encoding="utf-8")
        self.assertIn("-psn_", content)

    def test_build_macos_plist_validity(self):
        """Verify the Info.plist template generated by build_macos.sh is valid plist XML."""
        import plistlib
        import re

        script_file = self.macos_pkg_dir / "build_macos.sh"
        content = script_file.read_text(encoding="utf-8")

        # Extract plist XML block between cat > "${APP_BUNDLE}/Contents/Info.plist" <<EOF and EOF
        match = re.search(r'cat > "\$\{APP_BUNDLE\}/Contents/Info\.plist" <<EOF\s*\n(.*?)\nEOF', content, re.DOTALL)
        self.assertIsNotNone(match, "Could not find Info.plist template in build_macos.sh")
        plist_raw = match.group(1).replace("${APP_NAME}", "Antigravity Chat Migrator")

        # Parse with plistlib
        data = plistlib.loads(plist_raw.encode("utf-8"))
        self.assertEqual(data["CFBundleExecutable"], "agy-migrator")
        self.assertEqual(data["CFBundlePackageType"], "APPL")
        self.assertTrue(data["NSHighResolutionCapable"])


if __name__ == "__main__":
    unittest.main()
